version: '3.8'

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - "4002:4000"
    restart: on-failure
    env_file: .env
    volumes:
      - .:/cube/conf
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=calc
    image: mysql:8.0
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    ports:
      - 3307:3306
  redis:
    image: redis:6
    restart: always
